### PR TITLE
Added jblue5 to fall 2016

### PR DESCRIPTION
**Pull request by jblue5**

### CODE REVIEW

**Comment by mbMosman** [comment]
You've got no data in your file.... make sure to check it on your computer, you might have done the add & commit before you saved.

**Comment by jblue5** [comment]
Hello Mrs. Mosman,
I believe the error has been corrected. It took a couple more attempts to catch where my error was, but I now understand the importance of the workflow. 
Thank you
-Jorge Blue

**Comment by mbMosman** [comment]
Awesome!  Looks better now.

**Comment by mbMosman** [comment]
Woulda been better if you'd updated that emoji... always curious what that says about people.  💭

**Pull request merged**
